### ISSUE TITLE
Mouse not activated

### ISSUE THREAD

**Issue by kpishere** [lampmerchant/tashtrio#1]
HI, thanks for your work here!

I'm attempting to use this.  I had to update the ASM to an S file and made some changes for the new assembler (what a pain!).

There seems to be some life in the device now.  At power up though, the signal sent to the mouse does not look right.  On the left, you see the clock and data lines for the mouse, on the right you see what it is supposed to be.

Is the waveform on the left what you would expect it to be?  Or, are there issues from my translation from ASM to S?
![Screen Shot 2023-06-03 at 5 01 03 PM](https://github.com/lampmerchant/tashtrio/assets/25204173/75dceaa5-5cb6-479b-8faf-64105fdd0c94)

**Comment by kpishere** [comment]
I've pushed my changes to this forked branch.  [fork](https://github.com/kpishere/tashtrio.git)

**Comment by lampmerchant** [comment]
It seems like what you're looking at is the mouse sending an `0xAA` to the PIC to signal that its self-test completed successfully.  That's device-to-host communication, not host-to-device communication - as such, data is clocked out on the falling edge rather than the rising edge and there are 11 edges rather than 12 because there is no ACK bit.

The waveform looks like expected behavior to me; when power is applied, the mouse should send an `0xAA` to signal that its self-test completed successfully, followed by an `0x00` to identify itself as a mouse, and the PIC should respond with an `0xF4` to tell it to start sending data.  Is that not happening?

**Comment by kpishere** [comment]
Oh, ok.  Thanks for setting me straight.  The PIC does not respond.  But now I can put my focus on interrupt behaviour.  Perhaps my translation to .S has disturbed how that works.

**Comment by kpishere** [comment]
Thank you for your support!  Problem resolved.  The first two PSECT directives I did not update correctly and vector table was in wrong place.  I've pushed the fixes to my fork.  Let me know if you want a pull request.
