### ISSUE TITLE
Keyboard not working

### ISSUE THREAD

**Issue by kpishere** [lampmerchant/tashtrio#2]
Thought I was done! ;)

When checking the keyboard, there is no response.  Note that in the .S version [here](https://github.com/kpishere/tashtrio/blob/main/firmware/tashtrio.s) I'd enabled the default feature (LVP to ON value).  I noticed you had LVP = OFF.  This is the pin the keyboard data signal is on.  Is it an electrical requirement for LVP to be OFF for the keyboard to work?  That would explain why I see signal but no action from chip. (I only have a PICit 2 and would have to wire up a janky transistor on breadboard with extra power supply to do high voltage programming)

I've attached signal and response on ADB from mouse click and then one from keyboard where I press 'a' character.
 
Mouse:
![Screen Shot 2023-06-04 at 8 28 42 AM](https://github.com/lampmerchant/tashtrio/assets/25204173/45ee71b8-9255-4856-af6f-9f4a0c982b38)

Keyboard:
![Screen Shot 2023-06-04 at 8 29 31 AM](https://github.com/lampmerchant/tashtrio/assets/25204173/03141e81-dff1-4849-84b5-eb22dbc1ee4a)

**Comment by lampmerchant** [comment]
It is certainly possible that LVP needs to be turned off for the keyboard to be able to use RA3.  I've never used it, but my (limited) understanding is that LVP is activated by flashing some kind of bit pattern at RA3 and I'm not sure what implications that has for any other function RA3 is supposed to perform.  You might consider picking up a PICkit3 to do high-voltage programming on the PIC; they can be had fairly cheaply from eBay sellers since they're last-generation.

**Comment by kpishere** [comment]
Pulled out the data sheet, I knew there was something different about RA3 -- it can only function as an input pin.  No output on that pin.  LVP=ON or LVP=OFF should not make a difference as I'd feared.

In your code, I see you are presuming that it can be an output pin.  Is it critical though that output work for a keyboard?  Perhaps you are trying to set the keyboard lights and this is why that feature does not work? 

Example of where you are trying to clear TRISA but it is always 1 for RA3:
```
;WARNING: do NOT use RA2 for ADB, the Schmitt Trigger takes too long to react
AP_APIN	equ	PORTA_RA5_POSN	;Pin on PORTA where ADB bus is connected
PP_CPIN	equ	PORTA_RA2_POSN	;Pin on PORTA where PS/2 clock is connected
PP_KPIN	equ	PORTA_RA3_POSN	;Pin on PORTA where PS/2 keyboard is connected
PP_MPIN	equ	PORTA_RA4_POSN	;Pin on PORTA where PS/2 mouse is connected
;
; ....
;
Ps2FsaTxStrt:
	movlb	1		;Pull the appropriate data line low for the
	btfsc	PP_FLAG,PP_TXKI	; peripheral that we want to send a byte to
	bcf	TRISA,PP_KPIN	; "
	btfsc	PP_FLAG,PP_TXMI	; "
	bcf	TRISA,PP_MPIN	; "
	bsf	TRISA,PP_CPIN	;Release the clock line
	movlb	0		;Transition to the appropriate state for the
	btfsc	PP_FLAG,PP_TXKI	; peripheral that we want to send a byte to or
	retlw	low Ps2FsaTxKbSt; back to start if neither and we somehow got
	btfsc	PP_FLAG,PP_TXMI	; here by mistake
	retlw	low Ps2FsaTxMsSt; "
	retlw	low Ps2FsaStart	; "
```

**Comment by lampmerchant** [comment]
That code exists to generalize functionality - in case the pins are rearranged at some future point, i.e. that `PP_KPIN` is assigned somewhere else besides RA3, the code is already in place to allow host-to-device transmission for the keyboard.  `PP_KPIN` is assigned to RA3 because host-to-device communication is only needed to communicate the state of the LEDs to the keyboard, which we can do without (and the PIC12F1840 has no pins to spare).  In any case, it should have no bearing on the behavior you're seeing.

I looked into this a bit and according to [this](https://www.microchipdeveloper.com/8bit:lvp), whenever LVP is enabled, the RA3 pin is permanently set to the !MCLR function, meaning it can't be used as a digital input - looks like LVP is the culprit.

**Comment by kpishere** [comment]
Ah yeah, that is what I remember.  There was something ... thanks!  Indeed, it is fixed and worked.  I get one program with a PickIt 2 (with out a transistor mod .. ) and did it with LVP = OFF and it works, as it should.  Thanks!  (I'll push the change with a comment to my fork).

Also, thanks for doing this, in reviewing your code I learned.  I really like the state machine model!  I'm going to try that myself in next project.
